### ISSUE TITLE
Deneb BuilderBid.MarshalSSZ causes panic

### ISSUE THREAD

**Issue by benhenryhunter** [attestantio/go-builder-client#24]
When trying to use MarshalSSZ for deneb's BuilderBid type there is a panic while handling the *uint256.Int field.  If you modify it to match the capella SSZ method for value you can successfully Marshal the struct, but then unmarshaling from that output will fail with incorrect offsets in the `BlobKZGCommitments` field.

I've created some tests here that can be used to replicate the problem:  https://github.com/benhenryhunter/go-builder-client/pull/1

**Comment by mcdee** [comment]
Should be fixed in #25 please reopen if not.  Thanks.

**Comment by jzblox** [comment]
Awesome!
Is there an official release including this on the horizon?

**Comment by mcdee** [comment]
A new release with these changes has been made.
